### ISSUE TITLE
Some users see a 500 when trying to create an issue with additional custom fields

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#537]
I'm seeing a case where one users see's a 500 error in Mattermost when trying to create an issue. It seems like the 500 error begins to occur when you configure additional custom fields not supported by the integration as required. 
Strangely this does not occur for all users. Creating an issue with this same data from Jira works for this user.
![Create500](https://user-images.githubusercontent.com/35588783/81376438-8e688300-90d1-11ea-9b32-ff3110b260c3.PNG)

This occurred with Jira 2.4 and Jira Server 8.8

This error crashes the plugin. The debug logging below includes `panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"jira"}` 

```
{"level":"debug","ts":1588918752.4353971,"caller":"mlog/sugar.go:15","msg":"OK: ","plugin_id":"jira","Status":"200","Host":"dkh-sandbox.test.mattermost.cloud","RequestURI":"/plugins/jira/api/v2/get-create-issue-metadata-for-project?project-keys=PD","Method":"GET","query":"project-keys=PD"}
{"level":"debug","ts":1588918754.1862016,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"pzzixj1q7jn7zbnbp4ioedq9qr"}
{"level":"info","ts":1588918755.2118106,"caller":"cluster/cluster.go:349","msg":"This node attempted to join the cluster, but could not find any nodes."}
{"level":"debug","ts":1588918757.1863654,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"dzdhb85b7pywfc1p8n7rz3skhh"}
{"level":"debug","ts":1588918759.7383723,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"uc5p1a5mybruxcxrwgiemg1w3w"}
{"level":"debug","ts":1588918762.1864104,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"yir8qd3k97gbxr1joe3sn9zkty"}
{"level":"debug","ts":1588918764.186166,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"ozg4dk3gybdqbqouyzma7a1hbh"}
{"level":"debug","ts":1588918766.7610235,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"w7k5mq4jhpf48gkytmd1er97ka"}
{"level":"debug","ts":1588918767.1863163,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"6r3kgzsbu7foiyiibe4thp56ue"}
{"level":"info","ts":1588918770.212842,"caller":"cluster/cluster.go:349","msg":"This node attempted to join the cluster, but could not find any nodes."}
{"level":"debug","ts":1588918772.1865482,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"tze7c1m1wib37rpj7p1s3jryzo"}
{"level":"debug","ts":1588918773.6187236,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6187916,"caller":"plugin/hclog_adapter.go:53","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa0c35b]","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188223,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188354,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 197 [running]:","plugin_id":"jira"}
{"level":"debug","ts":1588918773.618848,"caller":"plugin/hclog_adapter.go:53","msg":"main.MakeCreateIssueURL(0xd427a0, 0xc00026a0f0, 0xc0002fb680, 0xc000524840, 0x0, 0x0)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188626,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-jira/server/client.go:312 +0x8fb","plugin_id":"jira"}
```

Steps:
- Create a custom fields not supported by the integration such as a radio button
- Make the filed mandatory
- From Mattermost, attempt to create an issue in the target project
**Expected**: Plugin posts `Please create your Jira issue manually. The project you tried to create an issue for has required fields this plugin does not yet support:`
**Observed** Create modal shows a 500 error for one of the usesr

**Comment by hanzei** [comment]
@DHaussermann There should be more related log messages below the last line. Could you also please post them here?

**Comment by DHaussermann** [comment]
@hanzei Here is everything in the DEBUG log after the error occurred:
```
"level":"debug","ts":1588918752.4353971,"caller":"mlog/sugar.go:15","msg":"OK: ","plugin_id":"jira","Status":"200","Host":"dkh-sandbox.test.mattermost.cloud","RequestURI":"/plugins/jira/api/v2/get-create-issue-metadata-for-project?project-keys=PD","Method":"GET","query":"project-keys=PD"}
{"level":"debug","ts":1588918754.1862016,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"pzzixj1q7jn7zbnbp4ioedq9qr"}
{"level":"info","ts":1588918755.2118106,"caller":"cluster/cluster.go:349","msg":"This node attempted to join the cluster, but could not find any nodes."}
{"level":"debug","ts":1588918757.1863654,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"dzdhb85b7pywfc1p8n7rz3skhh"}
{"level":"debug","ts":1588918759.7383723,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"uc5p1a5mybruxcxrwgiemg1w3w"}
{"level":"debug","ts":1588918762.1864104,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"yir8qd3k97gbxr1joe3sn9zkty"}
{"level":"debug","ts":1588918764.186166,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"ozg4dk3gybdqbqouyzma7a1hbh"}
{"level":"debug","ts":1588918766.7610235,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"w7k5mq4jhpf48gkytmd1er97ka"}
{"level":"debug","ts":1588918767.1863163,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"6r3kgzsbu7foiyiibe4thp56ue"}
{"level":"info","ts":1588918770.212842,"caller":"cluster/cluster.go:349","msg":"This node attempted to join the cluster, but could not find any nodes."}
{"level":"debug","ts":1588918772.1865482,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"tze7c1m1wib37rpj7p1s3jryzo"}
{"level":"debug","ts":1588918773.6187236,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6187916,"caller":"plugin/hclog_adapter.go:53","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa0c35b]","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188223,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188354,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 197 [running]:","plugin_id":"jira"}
{"level":"debug","ts":1588918773.618848,"caller":"plugin/hclog_adapter.go:53","msg":"main.MakeCreateIssueURL(0xd427a0, 0xc00026a0f0, 0xc0002fb680, 0xc000524840, 0x0, 0x0)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188626,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-jira/server/client.go:312 +0x8fb","plugin_id":"jira"}
{"level":"debug","ts":1588918773.618878,"caller":"plugin/hclog_adapter.go:53","msg":"main.httpAPICreateIssue(0xd427a0, 0xc00026a0f0, 0xd39ce0, 0xc000315600, 0xc00011c900, 0x868f61, 0xc0001d8d80, 0x0)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6188936,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-jira/server/issue.go:194 +0x901","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6189082,"caller":"plugin/hclog_adapter.go:53","msg":"main.withInstance(0x7f26779cf2e8, 0xc000108728, 0xd39ce0, 0xc000315600, 0xc00011c900, 0xc61560, 0xc000364ef8, 0x0, 0xc000022300)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6189244,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-jira/server/instance.go:83 +0xca","plugin_id":"jira"}
{"level":"debug","ts":1588918773.618938,"caller":"plugin/hclog_adapter.go:53","msg":"main.(*Plugin).serveHTTP(0xc0001b6480, 0xc000524600, 0xd39ce0, 0xc000315600, 0xc00011c900, 0x8a24e8, 0xd2bd20, 0x10)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6189837,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-jira/server/http.go:65 +0xb60","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6190195,"caller":"plugin/hclog_adapter.go:53","msg":"main.(*Plugin).ServeHTTP(0xc0001b6480, 0xc000524600, 0xd39ce0, 0xc000315600, 0xc00011c900)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6190376,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/src/github.com/mattermost/mattermost-plugin-jira/server/http.go:54 +0x74","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6190503,"caller":"plugin/hclog_adapter.go:53","msg":"github.com/mattermost/mattermost-server/v5/plugin.(*hooksRPCServer).ServeHTTP(0xc000113560, 0xc0003da340, 0x125a530, 0x0, 0x0)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6190631,"caller":"plugin/hclog_adapter.go:53","msg":"\t/Users/dylanhaussermann/go/pkg/mod/github.com/mattermost/mattermost-server/v5@v5.19.0/plugin/client_rpc.go:362 +0x29b","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6190784,"caller":"plugin/hclog_adapter.go:53","msg":"reflect.Value.call(0xc00005f380, 0xc00000e728, 0x13, 0xc0a379, 0x4, 0xc0002d1f08, 0x3, 0x3, 0xc0002c2eb0, 0x3, ...)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6190913,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/reflect/value.go:460 +0x8ab","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6191025,"caller":"plugin/hclog_adapter.go:53","msg":"reflect.Value.Call(0xc00005f380, 0xc00000e728, 0x13, 0xc0002c2f08, 0x3, 0x3, 0x100000000d1de80, 0x0, 0x5e34eb)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.619114,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/reflect/value.go:321 +0xb4","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6191254,"caller":"plugin/hclog_adapter.go:53","msg":"net/rpc.(*service).call(0xc000085ac0, 0xc000068730, 0xc00002e950, 0xc00002e960, 0xc0000c8780, 0xc00000d640, 0xab2d20, 0xc0003da340, 0x16, 0xac1020, ...)","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6191387,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/net/rpc/server.go:377 +0x17f","plugin_id":"jira"}
{"level":"debug","ts":1588918773.6191545,"caller":"plugin/hclog_adapter.go:53","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"jira"}
{"level":"debug","ts":1588918773.619165,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/net/rpc/server.go:474 +0x42b","plugin_id":"jira"}
{"level":"error","ts":1588918773.620201,"caller":"mlog/log.go:175","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"jira","error":"unexpected EOF"}
{"level":"debug","ts":1588918773.6202836,"caller":"plugin/hclog_adapter.go:51","msg":"plugin process exited","plugin_id":"jira","wrapped_extras":"pathplugins/jira/server/dist/plugin-linux-amd64pid313errorexit status 2"}
{"level":"debug","ts":1588918774.186192,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"ucb4zn4njjymbx3gx38pqkbgmo"}
{"level":"debug","ts":1588918774.3922322,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"wmpsas8fw7r78q6jo4ngni8i5c"}
{"level":"debug","ts":1588918777.1863782,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"sbz8hqzbb38m8e335wbspy4j6h"}
{"level":"debug","ts":1588918777.2068048,"caller":"plugin/supervisor.go:124","msg":"Error pinging plugin","error":"connection is shut down"}
{"level":"error","ts":1588918777.2068563,"caller":"plugin/health_check.go:59","msg":"Health check failed for plugin","id":"jira","error":"Plugin RPC connection is not responding"}
{"level":"debug","ts":1588918777.2068717,"caller":"plugin/health_check.go:65","msg":"Deactivating plugin due to multiple crashes","id":"jira"}
{"level":"warn","ts":1588918777.2069032,"caller":"plugin/hclog_adapter.go:69","msg":"error closing client during Kill","plugin_id":"jira","wrapped_extras":"errconnection is shut down"}
{"level":"warn","ts":1588918777.2069447,"caller":"plugin/hclog_adapter.go:71","msg":"plugin failed to exit gracefully","plugin_id":"jira"}
{"level":"debug","ts":1588918778.8155317,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"sb9sdspze3bk3brski3c4fhtta"}
{"level":"debug","ts":1588918779.524675,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"6474w8ebgi8njdgy8w5axwrdre"}
{"level":"debug","ts":1588918782.1864016,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"6r4ys8d84pfs5qs6h4tsxx8txe"}
{"level":"debug","ts":1588918784.1860535,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"9ioobjqtg3bnd81b5fjrq5ntsc"}
{"level":"info","ts":1588918785.2139292,"caller":"cluster/cluster.go:349","msg":"This node attempted to join the cluster, but could not find any nodes."}
{"level":"debug","ts":1588918787.1863897,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"hic8kjqj6tbzx8rpbpjku9ypuo"}
{"level":"debug","ts":1588918792.1862905,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"4yqpyf8bzjy5txhdtdrnu76hir"}
{"level":"debug","ts":1588918794.1860783,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"p6a7gytx57rffjf3b8554uxiky"}
{"level":"debug","ts":1588918797.1864116,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/system/ping","request_id":"9kkkoik1jfgz7x73j5o9579otc"}
{"level":"info","ts":1588918800.2148206,"caller":"cluster/cluster.go:349","msg":"This node attempted to join the cluster, but could not find any nodes."}
{"level":"debug","ts":1588918801.8844144,"caller":"web/handlers.go:85","msg":"Received HTTP request","method":"GET","url":"/api/v4/logs","request_id":"d8zjnfo8gib79f9a3cg5aaudth"}
```

**Comment by levb** [comment]
@DHaussermann when posting call-stacks, can you please include the PR/branch/commit link so that the line numbers can be matched later?

**Comment by mickmister** [comment]
@DHaussermann and I talked about this when he found the bug. The issue is this line

https://github.com/mattermost/mattermost-plugin-jira/blob/885efe8eb70c92bcea64d1ced6e67710eda77b6e/server/client.go#L311-L313

is expecting to have the `Reporter` defined by I assume this line

https://github.com/mattermost/mattermost-plugin-jira/blob/885efe8eb70c92bcea64d1ced6e67710eda77b6e/server/issue.go#L180-L182

but there is some somewhat complex logic that determines if it gets set.

We fill in the reporter when:
- Jira instance is Server
- and Reporter is in required fields

We try to use the reporter later when:
- Jira instance is Server

So I assume the issue happens when the instance is Server, but the Reporter is not required. Dylan said that it occurred for him even when the reporter was required, but I thought I'd share my findings from our conversation last week.
