### ISSUE TITLE
Travis release deployment doesn't work

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jira#8]
The release deployment of both `v1.0.1` and `v1.0.2` failed with:
```
[33mPreparing deploy[0m
Logged in as Chris
Deploying to repo: mattermost/mattermost-plugin-jira
Current tag is: v1.0.2

travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
Setting target_commitish to 7419e8a0b3883497af435f59820a47a81185baa0

travis_fold:end:dpl.3
/home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/mattermost/mattermost-plugin-jira/releases/14509117: 404 - Not Found // See: https://developer.github.com/v3/repos/releases/#edit-a-release (Octokit::NotFound)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `patch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:46:in `patch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/client/releases.rb:55:in `update_release'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.6/lib/dpl/provider/releases.rb:154:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by hanzei** [comment]
I have no idea why this isn't working.

If someone wants to give this a try, go ahead.

**Comment by cpanato** [comment]
i will check, adding on my backlog

**Comment by hanzei** [comment]
Site note: We are still using the login information from Chris Brown. Might be a good time to change this.

**Comment by cpanato** [comment]
now i know why this is failing :) i will fix that thanks @hanzei

**Comment by hanzei** [comment]
I did some minor changes on the [`8_fix-releases`](https://github.com/mattermost/mattermost-plugin-jira/commits/8_fix-release) branch. Please use this as a starting point.

**Comment by cpanato** [comment]
@hanzei I've updated the credentials for deploy in the [`8_fix-releases`](https://github.com/mattermost/mattermost-plugin-jira/commits/8_fix-release) branch
can you check if that works when you have some time? thanks!

**Comment by hanzei** [comment]
I cut a test release and it didn't work, see https://travis-ci.org/mattermost/mattermost-plugin-jira/builds/492901140?utm_source=github_status&utm_medium=notification

**Comment by cpanato** [comment]
I will check tomorrow. Please delete the test release

**Comment by cpanato** [comment]
can you try again when you have time? @hanzei

**Comment by hanzei** [comment]
Sure will do.

**Comment by hanzei** [comment]
That did work. Thanks Carlos!
